### ISSUE TITLE
Convert hard links to Django url tags in templates

### ISSUE THREAD

**Issue by hseritt** [hseritt/repositext#12]
Convert links in html pages like this:

<a href="/docweb/repository/folder/{{ doc.parent.id }}/">

to use Django url directives:

https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#url

**Comment by vidhibagadia** [comment]
Working on this if nobody else has taken this up.

**Comment by hseritt** [comment]
Closing this one. Thanks for your help!
