### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by hseritt** [hseritt/repositext#3]
We need to implement simple authentication into the app. There should be a login page and users would login there and wouldn't be able to access any part of the current app without logging in successfully. There also should be a link in the header that allows a user to log out.

ETA: Here are the requirements and I've done a less than stellar job at describing it in my initial post but here goes:

We want to keep the login piece inside of the docweb app. The docweb app is the actual app that will handle *all* of the UI (at least for now -- we can segment it later but for now we're using apps.docweb). 

We want to continue to use the styles.css for now. We'll change that eventually. We may use bootstrap or not.

We also want to keep the same header even on the login page.

Also, the functionality for logout should redirect the user to a login page and not to a blank one.

We also do not need to set up registration at this point especially since this is more of a deliverable or shrink-wrap type of application -- that is, one that we can package and someone can download and install and use. They can then run it on-premise. But, we also may want to consider a cloud version and registration will be necessary.

**Comment by mridubhatnagar** [comment]
Hi @hseritt
I am interested in contributing to this.

**Comment by hseritt** [comment]
Thanks! If you would, go ahead and clone the project, create a local branch and start working on it if you like. Once you get something going with it (some working code or at least some good suggestions), I'll go ahead and assign this one to you. If you have any questions on anything at all, feel free to message me directly (here or Twitter is fine).

**Comment by hseritt** [comment]
Keep in mind that at this point, we can simply just add the standard login functionality as described in django docs here:

https://docs.djangoproject.com/en/3.0/topics/auth/default/#module-django.contrib.auth.views

or if you have something else in mind.

**Comment by mridubhatnagar** [comment]
> Keep in mind that at this point, we can simply just add the standard login functionality as described in django docs here:
> 
> https://docs.djangoproject.com/en/3.0/topics/auth/default/#module-django.contrib.auth.views
> 
> or if you have something else in mind.

Yes, I was thinking of having a separate template and view for login and sign up pages. As for allowing a user to login first they need to be registered.

**Comment by hseritt** [comment]
Sounds good! Let's see what you come up with :-)

**Comment by mridubhatnagar** [comment]
Hey, I on this. There was some versioning issue. Will start pushing changes on my branch by weekend.

**Comment by hseritt** [comment]
No problem. Thanks for letting me know!

-Harlin

**Comment by mridubhatnagar** [comment]
The current view of https://127.0.0.1:8000/docweb/ is this. 
![Screenshot from 2020-02-29 13-08-23](https://user-images.githubusercontent.com/16894718/75603482-bd241500-5af4-11ea-8493-e923c1cf75a7.png)


Should we make it like? This first dashboard view is visible only when the user is logged in?
If the user is not logged in we show two buttons. Log In and Sign Up. Once the user is logged in then all of this is visible?

**Comment by mridubhatnagar** [comment]
I just cloned the project. And started working on it. Now, I am unable to push the changes. As the remote is set to your repo. 

Do I need to fork and add the forked repo's url as remote?

**Comment by hseritt** [comment]
Hi Mridu,
I've sent you a private note about this issue and pull request.
Thanks!
Harlin

**Comment by hseritt** [comment]
I've also modified the initial description of the issue with the requirements above. I hope this is more helpful than what I've put up before.

**Comment by mridubhatnagar** [comment]
Replied with some of the questions here https://github.com/hseritt/repositext/issues/2. 

1. Once you share a rough sketch or wireframe for login. I'll do the needful changes and push those.
2. Meanwhile, I can remove the user's app. And, add those changes in docweb app.

**Comment by hseritt** [comment]
I've merged your last pull request. Thanks!
