### ISSUE TITLE
Handle no child documents or folders in folder view

### ISSUE THREAD

**Issue by hseritt** [hseritt/repositext#7]
In the folder view template there should be a way to handle a situation where there are no child folders or no child documents in the view. There should be something like "No documents/folders" or "N/A" would be ok.

**Comment by vidhibagadia** [comment]
Hi @hseritt 
I'd like to contribute and start with this issue.

Is the desired behaviour:
1) The message only if documents/folders don't exist
OR
2) The message under the 'Folders'/'Documents' heading if items don't exist?

**Comment by hseritt** [comment]
Sounds like number 2. There should be a similar message for both Folders or Documents that would say N/A or No "object" (object being Document or Folder) for each.

**Comment by hseritt** [comment]
Sounds like number 2. There should be a similar message for both Folders or Documents that would say N/A or No "object" (object being Document or Folder) for each.

**Comment by hseritt** [comment]
I see it. I'll have a look today in more detail. Thank you very much :-)

**Comment by hseritt** [comment]
This has been merged and closing this one. Thanks!
